name: Deploy to production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          target: shop.bootcamp.place/server
          env-auth: ${{ secrets.AUTH_ENV_FILE }}
          env-shop: ${{ secrets.SHOP_ENV_FILE }}
          env-payments: ${{ secrets.PAYMENTS_ENV_FILE }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
